version: 1.2
workflows:
 - name: ecoli_char
   subclass: WDL
   primaryDescriptorPath: /ecoli_char.wdl
   testParameterFiles:
    - empty.json
 - name: de_novo_assembly
   subclass: WDL
   primaryDescriptorPath: /de_novo_assembly.wdl
   testParameterFiles:
    - empty.json
 - name: compile_ecoli
   subclass: WDL
   primaryDescriptorPath: /compile_ecoli_results.wdl
   testParameterFiles:
    - empty.json
